LIST_CIUDAD = [
        "ALL",
        "GUAYAQUIL",
        "QUITO",
        "CUENCA",
        "SANTO DOMINGO",
        "MACHALA",
        "DURAN",
        "MANTA",
        "PORTOVIEJO",
        "LOJA",
        "AMBATO",
        "ESMERALDAS",
        "QUEVEDO",
        "RIOBAMBA",
        "MILAGRO",
        "IBARRA",
        "LA LIBERTAD",
        "BABAHOYO",
        "SANGOLQUÍ",
        "DAULE",
        "LATACUNGA",
        "TULCÁN",
        "CHONE",
        "PASAJE",
        "SANTA ROSA",
        "NUEVA LOJA",
        "HUAQUILLAS",
        "EL CARMEN",
        "MONTECRISTI",
        "SAMBORONDÓN",
        "PUERTO FRANCISCO DE ORELLANA",
        "JIPIJAPA",
        "SANTA ELENA",
        "OTAVALO",
        "CAYAMBE",
        "BUENA FE",
        "VENTANAS",
        "VELASCO IBARRA",
        "LA TRONCAL",
        "EL TRIUNFO",
        "SALINAS",
        "GENERAL VILLAMIL",
        "AZOGUES",
        "PUYO",
        "VINCES",
        "LA CONCORDIA",
        "ROSA ZÁRATE",
        "BALZAR",
        "NARANJITO",
        "NARANJAL",
        "GUARANDA",
        "LA MANÁ",
        "TENA",
        "SAN LORENZO",
        "CATAMAYO",
        "EL GUABO",
        "PEDERNALES",
        "ATUNTAQUI",
        "BAHÍA DE CARÁQUEZ",
        "PEDRO CARBO",
        "MACAS",
        "YAGUACHI",
        "CALCETA",
        "ARENILLAS",
        "JARAMIJÓ",
        "VALENCIA",
        "MACHACHI",
        "SHUSHUFINDI",
        "ATACAMES",
        "PIÑAS",
        "SAN GABRIEL",
        "GUALACEO",
        "LOMAS DE SARGENTILLO",
        "CAÑAR",
        "CARIAMANGA",
        "BAÑOS DE AGUA SANTA",
        "MONTALVO",
        "MACARÁ",
        "SAN MIGUEL DE SALCEDO",
        "ZAMORA",
        "PUERTO AYORA",
        "LA JOYA DE LOS SACHAS",
        "SALITRE",
        "TOSAGUA",
        "PELILEO",
        "PUJILÍ",
        "TABACUNDO",
        "PUERTO LÓPEZ",
        "SAN VICENTE",
        "SANTA ANA",
        "ZARUMA",
        "BALAO",
        "ROCAFUERTE",
        "YANTZAZA",
        "COTACACHI",
        "SANTA LUCÍA",
        "CUMANDÁ",
        "PALESTINA",
        "ALFREDO BAQUERIZO MORENO",
        "NOBOL",
        "MOCACHE",
        "PUEBLOVIEJO",
        "PORTOVELO",
        "SUCÚA",
        "CANTON GUANO",
        "PÍLLARO",
        "SIMÓN BOLÍVAR",
        "GUALAQUIZA",
        "PAUTE",
        "SAQUISILÍ",
        "CNEL. MARCELINO MARIDUEÑA",
        "PAJÁN",
        "SAN MIGUEL",
        "PUERTO BAQUERIZO MORENO",
        "CATACOCHA",
        "PALENQUE",
        "ALAUSÍ",
        "CALUMA",
        "CATARAMA",
        "FLAVIO ALFARO",
        "COLIMES",
        "ECHEANDÍA",
        "JAMA",
        "GRAL. ANTONIO ELIZALDE (BUCAY)",
        "ISIDRO AYORA",
        "MUISNE",
        "SANTA ISABEL",
        "PEDRO VICENTE MALDONADO",
        "BIBLIÁN",
        "ARCHIDONA",
        "JUNÍN",
        "BABA",
        "VALDEZ (LIMONES)",
        "PIMAMPIRO",
        "CAMILO PONCE ENRÍQUEZ",
        "SAN MIGUEL DE LOS BANCOS",
        "EL TAMBO",
        "QUINSALOMA",
        "EL ÁNGEL",
        "ALAMOR",
        "CHAMBO",
        "CHIMBO",
        "CELICA",
        "CHORDELEG",
        "BALSAS",
        "SARAGURO",
        "EL CHACO",
        "GIRÓN",
        "HUACA",
        "PICHINCHA",
        "CHUNCHI",
        "PALLATANGA",
        "MARCABELÍ",
        "SÍGSIG",
        "GRAL. LEONIDAS PLAZA GUTIÉRREZ (LIMÓN)",
        "URCUQUÍ",
        "LORETO",
        "RIOVERDE",
        "ZUMBA",
        "PALORA",
        "MIRA",
        "EL PANGUI",
        "PUERTO QUITO",
        "BOLÍVAR",
        "SUCRE",
        "CHILLANES",
        "QUERO",
        "GUAMOTE",
        "CEVALLOS",
        "ZAPOTILLO",
        "VILLA LA UNIÓN (CAJABAMBA)",
        "SANTIAGO DE MÉNDEZ",
        "ZUMBI",
        "PUERTO EL CARMEN DE PUTUMAYO",
        "PATATE",
        "OLMEDO",
        "PUERTO VILLAMIL",
        "EL DORADO DE CASCALES",
        "LUMBAQUI",
        "PALANDA",
        "SIGCHOS",
        "PINDAL",
        "GUAYZIMI",
        "BAEZA",
        "EL CORAZÓN",
        "PACCHA",
        "AMALUZA",
        "LAS NAVES",
        "LOGROÑO",
        "SAN FERNANDO",
        "GONZANAMÁ",
        "SAN JUAN BOSCO",
        "YACUAMBI",
        "SANTA CLARA",
        "ARAJUNO",
        "TARAPOA",
        "TISALEO",
        "SUSCAL",
        "NABÓN",
        "MOCHA",
        "LA VICTORIA",
        "GUACHAPALA",
        "SANTIAGO",
        "CHAGUARPAMBA",
        "PENIPE",
        "TAISHA",
        "CHILLA",
        "PAQUISHA",
        "CARLOS JULIO AROSEMENA TOLA",
        "SOZORANGA",
        "PUCARÁ",
        "HUAMBOYA",
        "QUILANGA",
        "OÑA",
        "SEVILLA DE ORO",
        "MERA",
        "PABLO SEXTO",
        "OLMEDO",
        "DÉLEG",
        "LA BONITA",
        "EL PAN",
        "TIPUTINI",
        "BUCAY",
        "LA MANA",
        "LOS ANDES",
        "SALCEDO",
        "EL COCA (Puerto Francisco de Orellana)",
        "SIGSIG",
        "QUININDE",
    ]
